// tina/config.ts
import { defineConfig } from "tinacms";
var branch = process.env.GITHUB_BRANCH || process.env.VERCEL_GIT_COMMIT_REF || process.env.HEAD || "main";
var config_default = defineConfig({
  branch,
  // Get this from tina.io (optional for local-only mode)
  // clientId: process.env.TINA_CLIENT_ID,
  // token: process.env.TINA_TOKEN,
  build: {
    outputFolder: "admin",
    publicFolder: "public"
  },
  media: {
    tina: {
      mediaRoot: "uploads",
      publicFolder: "public"
    }
  },
  // Optional Tina search (requires TinaCloud indexer token)
  // search: {
  //   tina: {
  //     indexerToken: process.env.TINA_SEARCH_TOKEN,
  //     stopwordLanguages: ["eng"],
  //   },
  // },
  schema: {
    collections: [
      {
        name: "docs",
        label: "Documentation",
        path: "src/content/docs",
        format: "mdx",
        ui: {
          filename: {
            readonly: false,
            slugify: (values) => {
              return values?.title?.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "") || "untitled";
            }
          },
          // Default values when creating a new document
          defaultItem: () => ({
            title: "New Page",
            description: "",
            template: "doc",
            draft: false,
            pagefind: true
          }),
          /**
           * Visual-editing router – tells the admin which live URL
           * corresponds to a given document so it can open the page
           * in the iframe preview with click-to-edit.
           *
           * relativePath examples:
           *   "index.mdx"              → /
           *   "getting-started.mdx"    → /getting-started/
           *   "guides/pages.mdx"       → /guides/pages/
           *   "de/getting-started.mdx" → /de/getting-started/
           */
          router: ({ document }) => {
            const path = document._sys?.relativePath ?? document._sys?.filename ?? "";
            const withoutExt = path.replace(/\.(mdx?|md)$/, "");
            if (!withoutExt || withoutExt === "index") return "/";
            return `/${withoutExt}/`;
          }
        },
        fields: [
          // ---------- Core Starlight frontmatter ----------
          {
            type: "string",
            name: "title",
            label: "Title",
            isTitle: true,
            required: true
          },
          {
            type: "string",
            name: "description",
            label: "Description",
            ui: {
              component: "textarea"
            }
          },
          {
            type: "string",
            name: "slug",
            label: "Slug (optional override)"
          },
          {
            type: "boolean",
            name: "draft",
            label: "Draft (exclude from production builds)"
          },
          {
            type: "boolean",
            name: "pagefind",
            label: "Index in search (Pagefind)",
            ui: {
              // default true in Starlight
            }
          },
          {
            type: "string",
            name: "template",
            label: "Page Template",
            options: [
              { value: "doc", label: "Doc (default)" },
              { value: "splash", label: "Splash (wide, no sidebar)" }
            ]
          },
          {
            type: "boolean",
            name: "editUrl",
            label: "Show Edit Link"
            // Starlight accepts string | boolean; boolean is simplest for the editor
          },
          {
            type: "boolean",
            name: "lastUpdated",
            label: "Show Last Updated"
          },
          // ---------- Sidebar ----------
          {
            type: "object",
            name: "sidebar",
            label: "Sidebar",
            fields: [
              {
                type: "string",
                name: "label",
                label: "Custom Sidebar Label"
              },
              {
                type: "number",
                name: "order",
                label: "Order"
              },
              {
                type: "boolean",
                name: "hidden",
                label: "Hidden from autogenerated sidebar"
              },
              {
                type: "object",
                name: "badge",
                label: "Badge",
                fields: [
                  {
                    type: "string",
                    name: "text",
                    label: "Text"
                  },
                  {
                    type: "string",
                    name: "variant",
                    label: "Variant",
                    options: [
                      "note",
                      "tip",
                      "caution",
                      "danger",
                      "success",
                      "default"
                    ]
                  }
                ]
              }
            ]
          },
          // ---------- Table of Contents ----------
          {
            type: "object",
            name: "tableOfContents",
            label: "Table of Contents",
            fields: [
              {
                type: "number",
                name: "minHeadingLevel",
                label: "Min Heading Level (1-6)"
              },
              {
                type: "number",
                name: "maxHeadingLevel",
                label: "Max Heading Level (1-6)"
              }
            ]
          },
          // ---------- Hero (for splash pages) ----------
          {
            type: "object",
            name: "hero",
            label: "Hero Section",
            fields: [
              {
                type: "string",
                name: "title",
                label: "Hero Title"
              },
              {
                type: "string",
                name: "tagline",
                label: "Tagline",
                ui: { component: "textarea" }
              },
              {
                type: "object",
                name: "image",
                label: "Hero Image",
                fields: [
                  {
                    type: "image",
                    name: "file",
                    label: "Image File"
                  },
                  {
                    type: "string",
                    name: "alt",
                    label: "Alt Text"
                  },
                  {
                    type: "image",
                    name: "dark",
                    label: "Dark Mode Image"
                  },
                  {
                    type: "image",
                    name: "light",
                    label: "Light Mode Image"
                  },
                  {
                    type: "string",
                    name: "html",
                    label: "Raw HTML (alternative to file)",
                    ui: { component: "textarea" }
                  }
                ]
              },
              {
                type: "object",
                name: "actions",
                label: "Call-to-Action Buttons",
                list: true,
                fields: [
                  {
                    type: "string",
                    name: "text",
                    label: "Button Text",
                    required: true
                  },
                  {
                    type: "string",
                    name: "link",
                    label: "Link URL",
                    required: true
                  },
                  {
                    type: "string",
                    name: "variant",
                    label: "Variant",
                    options: ["primary", "secondary", "minimal"]
                  },
                  {
                    type: "string",
                    name: "icon",
                    label: "Icon Name (or SVG)"
                  }
                ]
              }
            ]
          },
          // ---------- Banner ----------
          {
            type: "object",
            name: "banner",
            label: "Announcement Banner",
            fields: [
              {
                type: "string",
                name: "content",
                label: "Banner Content (HTML allowed)",
                ui: { component: "textarea" }
              }
            ]
          },
          // ---------- Prev / Next ----------
          {
            type: "object",
            name: "prev",
            label: "Previous Page Link",
            fields: [
              { type: "string", name: "link", label: "Link" },
              { type: "string", name: "label", label: "Label" }
            ]
          },
          {
            type: "object",
            name: "next",
            label: "Next Page Link",
            fields: [
              { type: "string", name: "link", label: "Link" },
              { type: "string", name: "label", label: "Label" }
            ]
          },
          // ---------- Head tags ----------
          {
            type: "object",
            name: "head",
            label: "Custom Head Tags",
            list: true,
            fields: [
              {
                type: "string",
                name: "tag",
                label: "Tag Name",
                options: ["title", "meta", "link", "script", "style"]
              },
              {
                type: "string",
                name: "content",
                label: "Content"
              },
              {
                type: "object",
                name: "attrs",
                label: "Attributes",
                fields: [
                  { type: "string", name: "name", label: "Name" },
                  { type: "string", name: "content", label: "Content" },
                  { type: "string", name: "property", label: "Property" },
                  { type: "string", name: "href", label: "Href" },
                  { type: "string", name: "src", label: "Src" },
                  { type: "boolean", name: "defer", label: "Defer" }
                ]
              }
            ]
          },
          // ---------- Body (rich-text with Starlight component templates) ----------
          {
            type: "rich-text",
            name: "body",
            label: "Body",
            isBody: true,
            templates: [
              // Aside
              {
                name: "Aside",
                label: "Aside",
                fields: [
                  {
                    type: "string",
                    name: "type",
                    label: "Type",
                    options: ["note", "tip", "caution", "danger"]
                  },
                  {
                    type: "string",
                    name: "title",
                    label: "Title (optional)"
                  },
                  {
                    type: "rich-text",
                    name: "children",
                    label: "Content"
                  }
                ]
              },
              // Card
              {
                name: "Card",
                label: "Card",
                fields: [
                  {
                    type: "string",
                    name: "title",
                    label: "Title",
                    required: true
                  },
                  {
                    type: "string",
                    name: "icon",
                    label: "Icon Name"
                  },
                  {
                    type: "rich-text",
                    name: "children",
                    label: "Content"
                  }
                ]
              },
              // CardGrid
              {
                name: "CardGrid",
                label: "Card Grid",
                fields: [
                  {
                    type: "boolean",
                    name: "stagger",
                    label: "Stagger"
                  },
                  {
                    type: "rich-text",
                    name: "children",
                    label: "Cards (add Card components inside)"
                  }
                ]
              },
              // LinkCard
              {
                name: "LinkCard",
                label: "Link Card",
                fields: [
                  {
                    type: "string",
                    name: "title",
                    label: "Title",
                    required: true
                  },
                  {
                    type: "string",
                    name: "href",
                    label: "URL",
                    required: true
                  },
                  {
                    type: "string",
                    name: "description",
                    label: "Description"
                  },
                  {
                    type: "string",
                    name: "icon",
                    label: "Icon"
                  }
                ]
              },
              // Badge
              {
                name: "Badge",
                label: "Badge",
                fields: [
                  {
                    type: "string",
                    name: "text",
                    label: "Text",
                    required: true
                  },
                  {
                    type: "string",
                    name: "variant",
                    label: "Variant",
                    options: [
                      "note",
                      "tip",
                      "caution",
                      "danger",
                      "success",
                      "default"
                    ]
                  },
                  {
                    type: "string",
                    name: "size",
                    label: "Size",
                    options: ["small", "medium", "large"]
                  }
                ]
              },
              // Icon
              {
                name: "Icon",
                label: "Icon",
                fields: [
                  {
                    type: "string",
                    name: "name",
                    label: "Icon Name",
                    required: true
                  },
                  {
                    type: "string",
                    name: "color",
                    label: "Color"
                  },
                  {
                    type: "string",
                    name: "size",
                    label: "Size"
                  }
                ]
              },
              // Tabs / TabItem
              {
                name: "Tabs",
                label: "Tabs",
                fields: [
                  {
                    type: "string",
                    name: "syncKey",
                    label: "Sync Key (for synced tabs)"
                  },
                  {
                    type: "rich-text",
                    name: "children",
                    label: "Tab Items"
                  }
                ]
              },
              {
                name: "TabItem",
                label: "Tab Item",
                fields: [
                  {
                    type: "string",
                    name: "label",
                    label: "Label",
                    required: true
                  },
                  {
                    type: "string",
                    name: "icon",
                    label: "Icon"
                  },
                  {
                    type: "rich-text",
                    name: "children",
                    label: "Content"
                  }
                ]
              },
              // Steps
              {
                name: "Steps",
                label: "Steps",
                fields: [
                  {
                    type: "rich-text",
                    name: "children",
                    label: "Step Items"
                  }
                ]
              },
              // FileTree
              {
                name: "FileTree",
                label: "File Tree",
                fields: [
                  {
                    type: "rich-text",
                    name: "children",
                    label: "Tree Structure (use markdown lists)"
                  }
                ]
              },
              // LinkButton
              {
                name: "LinkButton",
                label: "Link Button",
                fields: [
                  {
                    type: "string",
                    name: "href",
                    label: "URL",
                    required: true
                  },
                  {
                    type: "string",
                    name: "variant",
                    label: "Variant",
                    options: ["primary", "secondary", "minimal"]
                  },
                  {
                    type: "string",
                    name: "icon",
                    label: "Icon"
                  },
                  {
                    type: "rich-text",
                    name: "children",
                    label: "Button Text"
                  }
                ]
              }
            ]
          }
        ]
      },
      // Optional: i18n UI strings collection
      {
        name: "i18n",
        label: "UI Translations (i18n)",
        path: "src/content/i18n",
        format: "json",
        ui: {
          allowedActions: {
            create: true,
            delete: false
          }
        },
        fields: [
          {
            type: "string",
            name: "component_preview",
            nameOverride: "component.preview",
            label: "Component Preview Label"
          }
          // Add more keys as needed from the JSON files
        ]
      }
    ]
  }
});
export {
  config_default as default
};
